pdflatex 'Assignment 01 Solutions.tex'
pdflatex 'Assignment 01.tex'
pdflatex 'Assignment 02 Solutions.tex'
pdflatex 'Assignment 02.tex'
pdflatex 'Assignment 03 Solutions.tex'
pdflatex 'Assignment 03.tex'
pdflatex 'Assignment 04 Solutions.tex'
pdflatex 'Assignment 04.tex'
pdflatex 'Assignment 05 Solutions.tex'
pdflatex 'Assignment 05.tex'
pdflatex 'Assignment 06 Solutions.tex'
pdflatex 'Assignment 06.tex'
pdflatex 'Assignment 07.tex'
pdflatex 'Assignment 08.tex'
pdflatex 'Assignment 09 Solutions.tex'
pdflatex 'Assignment 09.tex'
pdflatex 'Assignment 10 Solutions.tex'
pdflatex 'Assignment 10.tex'
pdflatex 'Assignment 11 Solutions.tex'
pdflatex 'Assignment 11.tex'
pdflatex 'Assignment 12.tex'
pdflatex 'Assignment 13.tex'
pdflatex 'Assignment 14.tex'
pdflatex 'Essay Assignment.tex'
pdflatex 'Redemption for Exam 2.tex'
pdflatex 'Redemption for Exam 2 Solutions.tex'

